"""create user_save_progress

Revision ID: 25b721f03b19
Revises: bd03a30f058c
Create Date: 2023-05-23 17:31:14.042610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b721f03b19'
down_revision = 'bd03a30f058c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_save_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=255), nullable=False),
    sa.Column('save_flag', sa.Boolean(), nullable=False),
    sa.Column('valid_flag', sa.Boolean(), nullable=False),
    sa.Column('create_user', sa.String(length=40), nullable=False),
    sa.Column('create_datetime', sa.DateTime(), nullable=False),
    sa.Column('update_user', sa.String(length=40), nullable=False),
    sa.Column('update_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_save_progress')
    # ### end Alembic commands ###
