"""create user table

Revision ID: 754a90d10964
Revises: 959d11ffda4c
Create Date: 2023-05-23 15:57:36.636206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '754a90d10964'
down_revision = '959d11ffda4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('line_id', sa.String(length=255), nullable=False),
    sa.Column('valid_flag', sa.Boolean(), nullable=False),
    sa.Column('create_user', sa.String(length=40), nullable=False),
    sa.Column('create_datetime', sa.DateTime(), nullable=False),
    sa.Column('update_user', sa.String(length=40), nullable=False),
    sa.Column('update_datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
