"""create signup status in user table

Revision ID: bd03a30f058c
Revises: 754a90d10964
Create Date: 2023-05-23 16:18:26.794375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd03a30f058c'
down_revision = '754a90d10964'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('start_signup', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('end_signup', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'end_signup')
    op.drop_column('user', 'start_signup')
    # ### end Alembic commands ###
